services:
  db:
    image: my-hackerrank-db:1.0 # image name and tag
    build: . # '.' - get data from currect directory
    env_file:
      - .env
    ports:
      - "5434:5432" # computer port : container port
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: # Named volume for persisting database data